spring:
  data:
    redis:
      port: 6379
      host: 172.16.213.22
      password: H@6#sP3!a9*rD1$q5^w2&z8

  datasource:
    ## 카카오 클라우드 mysql
    ### Line 6 서비스에 따라 변경 필요, 현재 order임
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://az-a.dpang-database.70e895c2d22b44e79797ed89d4dc2b5c.mysql.managed-service.kr-gov-central-1.kakaocloud-kr-gov.com:3306/dpang_order?createDatabaseIfNotExist=true
    #    username: admin
    #    password: PwUYtotGFZVdDKrY

    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dpang_user?createDatabaseIfNotExist=true
    username: root
    password: 12345

  ## 서비스마다 수정
  application:
    name: shoppingmall-server

eureka:
  instance:
    prefer-ip-address: true

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #      defaultZone: http://172.16.3.68/eureka/  ## Private IP of LB
      ## Public IP of LB
      defaultZone: http://61.109.216.220/eureka/

jwt:
  secret-key: asdfasdfasdfasdfasdfasdfasdfasdfsadfasdfasdfasdf